//
// Created by Micah Strange on 01/10/2024.
//

#ifndef FILTERLIBRARY_MODULES_MOVINGAVERAGE_SRC_MOVINGAVERAGE_MOVINGAVERAGE_H_
#define FILTERLIBRARY_MODULES_MOVINGAVERAGE_SRC_MOVINGAVERAGE_MOVINGAVERAGE_H_

class MovingAverage
{
public:
private:
};

#endif // FILTERLIBRARY_MODULES_MOVINGAVERAGE_SRC_MOVINGAVERAGE_MOVINGAVERAGE_H_
